### ISSUE TITLE
status 422 errors

### ISSUE THREAD

**Issue by jgedeon120** [csirtgadgets/massive-octo-spice#270]
Updated to the latest master, now getting status 422 errors on both the server and the client.

[2015-07-07T08:40:20,318Z][INFO]: starting up client...
[2015-07-07T08:40:20,318Z][INFO]: running search...
[2015-07-07T08:40:51,238Z][INFO]: status: 422
invalid request at /usr/local/bin/cif line 261.

**Comment by wesyoung** [comment]
what was the search?

**Comment by giovino** [comment]
I'll spin up a beta-11 instance now to try to duplicate. stay tuned.

**Comment by jgedeon120** [comment]
I'm seeing this in the elasticsearch logs.
[2015-07-07 08:57:25,671][DEBUG][action.search.type       ] [Jack Flag] [cif.observables-2015.06.01][2], node[Wo5XbzWqTVG9A_ViyKmJxA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@5ca270b6] lastShard [true]
org.elasticsearch.search.query.QueryPhaseExecutionException: [cif.observables-2015.06.01][2]: query[ConstantScore(+cache(group:everyone) +cache(provider:alexa.com))],from[0],size[500000],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@34832db9>!]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:272)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:283)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by jgedeon120** [comment]
Wes, any search, I just tried cif -vn -q 8.8.8.8

**Comment by jgedeon120** [comment]
After I increased the ES_HEAP_SIZE in elasticsearch it looks like things are working again.  A little more testing.

**Comment by jgedeon120** [comment]
Nope, still getting the 422's randomly.

**Comment by jgedeon120** [comment]
It surely does look related to elasticsearch.

[2015-07-07T09:17:00,498Z][ERROR]: [Timeout] ** [http://localhost:9200]-[599] Timed out while waiting for socket to become ready for reading, called from sub Search::Elasticsearch::Transport::try {...}  at /usr/share/perl5/Try/Tiny.pm line 81. With vars: {'status_code' => 599,'request' => {'path' => '/cif.observables-%2A/_search','body' => {'query' => {'filtered' => {'filter' => {'and' => [{'or' => [{'term' => {'group' => ['everyone']}}]},{'term' => {'otype' => 'ipv4'}},{'regexp' => {'observable' => '104.*'}}]}}},'sort' => [{'@timestamp' => {'order' => 'desc'}}]},'mime_type' => 'application/json','serialize' => 'std','ignore' => [],'qs' => {'size' => 500000},'method' => 'GET'}}

**Comment by giovino** [comment]
Q1: How much memory are you allocating to the machine running CIF? ($ /usr/bin/free -m)?
Q2: Are you inserting a lot of data that isn't shipped by default?
Q3: Did you do a clean install of beta-11 or an upgrade?

**Comment by giovino** [comment]
FYI. I just completed a clean install of cif-beta-11 in a VM, I'm not seeing any issues at this time.

**Comment by jgedeon120** [comment]
Q1: How much memory are you allocating to the machine running CIF? ($ /usr/bin/free -m)?
16GB on the system, looks like about 11GB is being used.

Q2: Are you inserting a lot of data that isn't shipped by default?
Not by much. Maybe 5 feeds or so.

Q3: Did you do a clean install of beta-11 or an upgrade?
Upgrade, followed upgrade handling #110 issue.

**Comment by jgedeon120** [comment]
cif -vn -q 104.245.96.96
[2015-07-07T09:25:59,677Z][INFO]: starting up client...
[2015-07-07T09:25:59,677Z][INFO]: running search...
[2015-07-07T09:28:00,417Z][INFO]: status: 500
<!DOCTYPE html>
<html>
  <head><title>Server error</title></head>
  <style>
      body { background-color: #caecf6 }
      #raptor {
        background: url(/mojo/failraptor.png);
        height: 488px;
        left: 50%;
        margin-left: -371px;
        margin-top: -244px;
        position:absolute;
        top: 50%;
        width: 743px;
      }
    </style>
  <body><div id="raptor"></div></body>
</html>
 at /usr/local/bin/cif line 288.

**Comment by jgedeon120** [comment]
Seeing this in the cif-starman logs.

[Tue Jul  7 09:31:21 2015] [error] Can't use string ("0") as a HASH ref while "strict refs" in use at /opt/cif/bin/../lib/perl5/CIF/Client.pm line 217.

**Comment by giovino** [comment]
hmm admittedly we are not testing upgrades nearly as much at this stage.  browsing through the commits, nothing sticks out at me that would "break" in an upgrade.

**Comment by jgedeon120** [comment]
I didn't think so either.

**Comment by wesyoung** [comment]
some things i've noticed when "upgrading" (which we need to think through):

1. remove /opt/cif first, then run easy button
2. restart elasticsearch
3. make sure all cif-services (cif-router, cif-worker and cif-starman) are completely killed (ps aux | grep cif)

sometimes these services are in the middle of something, so while the easybutton makes it seem like they've been restarted, sometimes they haven't... (or are stuck or..)

**Comment by giovino** [comment]
I read through the "easy button", re-running that could clobber some some things (postfix changes) as one example.

**Comment by giovino** [comment]
I am able to duplicate on cif-beta-11:

```
/usr/local/bin/cif -q 200.87.139.154
invalid request at /usr/local/bin/cif line 288.
```

Turned on debug logs, do not see anything special. 

@wesyoung I found an IP that failed with this:

```
cif --otype ipv4 -f csv | cut -d',' -f4 > ips
```

vim cif_query.sh
```
#!/bin/bash

while read i; do
    echo "querying: $i"
    /usr/local/bin/cif -q $i
done<ips
```

**Comment by jgedeon120** [comment]
A fresh install this morning.

cif -vn -q 200.87.139.154
[2015-07-08T07:29:25,539Z][INFO]: starting up client...
[2015-07-08T07:29:25,539Z][INFO]: running search...
[2015-07-08T07:29:27,344Z][INFO]: status: 422
invalid request at /usr/local/bin/cif line 288.

Found in cif-router.log:
[2015-07-08T07:29:27,339Z][ERROR]: invalid key at /opt/cif/bin/../lib/perl5/CIF/Storage/ElasticSearch.pm line 410.

**Comment by wesyoung** [comment]
everything looks a-OK with no data in the pod, i'm pushing data into a test instance, see if i can reproduce it..

**Comment by wesyoung** [comment]
```
[2015-07-08T12:01:15,376Z][DEBUG][CIF::Storage::ElasticSearch:411]: 200.147.3.199
[2015-07-08T12:01:15,377Z][DEBUG][CIF::Storage::ElasticSearch:410]: $VAR1 = {
          'confidence' => 75,
          'otype' => 'ipv4',
          'group' => [
                       'everyone'
                     ],
          'observable' => '2001:da8:8001:2303:b58f:25b4:a6fc:509d',
          '@timestamp' => '2015-07-08T11:51:12.934Z',
          'id' => '8d94a8787789b8f2e47a47ab6834e8ddb7d38a1742f7453e7ed3bfe959f91588',
          'tlp' => 'amber',
          '@version' => 2,
          'lasttime' => '2015-07-08T11:51:12Z',
          'altid_tlp' => 'green',
          'tags' => [
                      'bot'
                    ],
          'application' => 'smtp',
          'provider' => 'blocklist.de',
          'altid' => 'http://www.blocklist.de/en/view.html?ip=2001:da8:8001:2303:b58f:25b4:a6fc:509d',
          'reporttime' => '2015-07-08T11:44:26Z',
          'firsttime' => '2015-07-08T11:51:12Z',
          'lang' => 'EN'
        };

```

what the shit?

**Comment by wesyoung** [comment]
blocklist.de was intermixing ipv6 and ipv4, and there was a bug somewhere in the rule processing between the two (coincidence with beta.11, not because of).

need to do some more testing, will try to release another beta this aft...

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/releases/tag/2.00.00-beta.12

**Comment by jgedeon120** [comment]
Initial testing looks like things are working again in my test
environment.  Nice work on the fast turn around.

On Wed, Jul 8, 2015 at 1:06 PM, Wes <notifications@github.com> wrote:

>
> https://github.com/csirtgadgets/massive-octo-spice/releases/tag/2.00.00-beta.12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csirtgadgets/massive-octo-spice/issues/270#issuecomment-119664980>
> .
>



-- 
Registered Linux User # 379282

**Comment by giovino** [comment]
Don't think this is fixed:

```
massive-octo-spice/src/bin$ bash version.sh -p
2.00.00-beta.12
```

```
$ cif --feed --otype ipv4
invalid request at /usr/local/bin/cif line 293.
```

Likely related:
```
[2015-07-09T14:54:41,429Z][ERROR]: [Request] ** [http://localhost:9200]-[500] {"error":"OutOfMemoryError[Java heap space]","status":500}, called from sub Search::Elasticsearch::Transport::try {...}  at /usr/share/perl5/Try/Tiny.pm line 81. With vars: {'status_code' => 500,'request' => {'qs' => {'size' => 500000},'mime_type' => 'application/json','method' => 'GET','serialize' => 'std','path' => '/cif.observables-%2A/_search','body' => {'query' => {'filtered' => {'filter' => {'and' => [{'or' => [{'term' => {'group' => ['everyone']}}]},{'term' => {'otype' => ['ipv4']}}]}}},'sort' => [{'@timestamp' => {'order' => 'desc'}}]},'ignore' => []}}
[2015-07-09T14:55:28,833Z][ERROR]: [Request] ** [http://localhost:9200]-[500] {"error":"OutOfMemoryError[Java heap space]","status":500}, called from sub Search::Elasticsearch::Transport::try {...}  at /usr/share/perl5/Try/Tiny.pm line 81. With vars: {'status_code' => 500,'request' => {'mime_type' => 'application/json','qs' => {'size' => 500000},'method' => 'GET','serialize' => 'std','body' => {'query' => {'filtered' => {'filter' => {'and' => [{'term' => {'otype' => ['ipv4']}},{'or' => [{'term' => {'group' => ['everyone']}}]}]}}},'sort' => [{'@timestamp' => {'order' => 'desc'}}]},'path' => '/cif.observables-%2A/_search','ignore' => []}}
[2015-07-09T14:56:45,022Z][ERROR]: [Request] ** [http://localhost:9200]-[500] {"error":"OutOfMemoryError[Java heap space]","status":500}, called from sub Search::Elasticsearch::Transport::try {...}  at /usr/share/perl5/Try/Tiny.pm line 81. With vars: {'request' => {'qs' => {'size' => 500000},'mime_type' => 'application/json','serialize' => 'std','method' => 'GET','ignore' => [],'path' => '/cif.observables-%2A/_search','body' => {'query' => {'filtered' => {'filter' => {'and' => [{'term' => {'otype' => ['ipv4']}},{'or' => [{'term' => {'group' => ['everyone']}}]}]}}},'sort' => [{'@timestamp' => {'order' => 'desc'}}]}},'status_code' => 500}
```

**Comment by wesyoung** [comment]
how much mem were you using? i'm guessing i need to bring down that hard limit from 50k to 10k or somethin...

**Comment by giovino** [comment]
```
free -m
             total       used       free     shared    buffers     cached
Mem:         12016       4636       7380          0         11        192
-/+ buffers/cache:       4432       7584
Swap:        12287       1552      10735
```

**Comment by giovino** [comment]
Turns out this the error I last submitted was a an out of memory issue, I was running this on a machine with 12GB of memory (lower than we recommend). The result of further testing will be to tune the ES search parameters.
